# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export GOPATH=~/go
export PATH=$GOPATH/bin:$PATH

# Nodenv init
export PATH="$HOME/.nodenv/bin:$PATH"
eval "$(nodenv init -)"

# Alias
alias kc=kubectl
alias tf=terraform
alias tff='terraform fmt -recursive'
alias tfw='terraform workspace'
alias Balus='terraform destroy'
alias g='git'
alias src='cd $(ghq root)/$(ghq list | peco)'
# alias chrepo ='cd $(ghq root)/$(ghq list | peco)'
alias vsrc='code -n $(ghq root)/$(ghq list | peco)'
alias dc='docker'
alias doc='docker-compose'
alias dcrm='docker rm $(docker ps -aq)'
alias cdsrc='cd $GOPATH/src'

eval $(thefuck --alias)

zshaddhistory() {
    local line=${1%%$'\n'}
    local cmd=${line%% *}

    [[ ${#line} -ge 5
        && ${cmd} != (terraform destroy|tf destroy|Balus)
    ]]
}

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
